# Generated by Django 3.2 on 2023-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0006_alter_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_with_terms',
            field=models.BooleanField(default=False),
        ),
    ]
