# Generated by Django 3.2 on 2023-09-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0008_alter_user_agree_with_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree_with_terms',
            field=models.BooleanField(default=False, help_text='Agree with terms', verbose_name='Agree with terms'),
        ),
    ]
