# Generated by Django 3.2 on 2023-09-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0009_alter_user_agree_with_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_with_privacy_policy',
            field=models.BooleanField(default=False, help_text='Agree with privacy policy', verbose_name='Agree with privacy policy'),
        ),
    ]
