# Generated by Django 4.1.13 on 2024-01-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ej_users", "0010_user_agree_with_privacy_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="signature",
        ),
    ]
