# Generated by Django 3.2 on 2023-08-18 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_conversations', '0019_alter_vote_channel'),
        ('ej_clusters', '0003_barbara_remove_clusterization_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_level', models.PositiveIntegerField()),
                ('clusters', models.ManyToManyField(to='ej_clusters.Cluster')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='ej_conversations.conversation')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(0, 'Skip'), (1, 'Agree'), (-1, 'Disagree')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.comment')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ej_activation.community')),
            ],
        ),
    ]
