# Generated by Django 3.2 on 2023-08-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_activation', '0002_alter_community_engagement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='engagement_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
