# Generated by Django 3.2 on 2023-08-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_activation', '0003_alter_community_engagement_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='community',
            name='engagement_level',
        ),
    ]
