# Generated by Django 3.2 on 2023-08-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_activation', '0004_auto_20230821_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
    ]
