# Generated by Django 3.2 on 2023-08-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0019_alter_vote_channel'),
        ('ej_activation', '0005_remove_community_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(0, 'Skip'), (1, 'Agree'), (-1, 'Disagree')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.comment')),
            ],
        ),
        migrations.RenameModel(
            old_name='Community',
            new_name='Segment',
        ),
        migrations.DeleteModel(
            name='CommunityVote',
        ),
        migrations.AddField(
            model_name='segmentvote',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ej_activation.segment'),
        ),
    ]
