# Generated by Django 3.2 on 2023-08-30 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0019_alter_vote_channel'),
        ('ej_clusters', '0003_barbara_remove_clusterization_counters'),
        ('ej_activation', '0006_auto_20230829_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_level', models.PositiveIntegerField(default=0)),
                ('comments', models.JSONField()),
                ('clusters', models.ManyToManyField(to='ej_clusters.Cluster')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.conversation')),
            ],
        ),
    ]
