# Generated by Django 3.2 on 2023-10-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_activation', '0007_segmentfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentVote',
        ),
    ]
