# Generated by Django 3.2 on 2023-11-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_activation', '0008_delete_segmentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
