# Generated by Django 3.2 on 2023-09-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0019_alter_vote_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='anonymous_votes_limit',
            field=models.IntegerField(default=0, help_text='Configures how many anonymous votes participants can give.', verbose_name='Anonymous votes'),
        ),
    ]
