# Generated by Django 3.2 on 2023-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0020_conversation_anonymous_votes_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
