# Generated by Django 3.2 on 2023-12-04 23:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0022_alter_conversation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='welcome_message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
