# Generated by Django 3.2 on 2023-12-05 23:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0023_conversation_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='welcome_message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A message to be presented to participants before starting voting.', null=True),
        ),
    ]
