# Generated by Django 4.1.13 on 2024-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0027_conversation_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="anonymous_votes_limit",
            field=models.IntegerField(
                default=0,
                help_text="Configures how many anonymous votes participants can give.",
                verbose_name="Number of anonymous votes",
            ),
        ),
    ]
