# Generated by Django 4.1.13 on 2024-03-22 01:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0028_alter_conversation_anonymous_votes_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="ending_message",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Text to be presented to participants in the end of voting.",
                null=True,
            ),
        ),
    ]
