# Generated by Django 3.2 on 2023-08-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0005_profile_completed_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filtered_home_tag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
